# Generated by Django 4.1.8 on 2023-04-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField(max_length=200)),
                ("product_type", models.CharField(choices=[("com", "Comida"), ("coc", "Cocteleria")], max_length=3)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
