# Generated by Django 4.1.8 on 2023-05-04 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("location_name", models.CharField(max_length=20)),
                ("description", models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField(max_length=200)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=6)),
                ("image", models.ImageField(null=True, upload_to="product-images/")),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sale_name", models.CharField(max_length=40)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20)),
                (
                    "product_type",
                    models.CharField(choices=[("com", "Comida"), ("beb", "Bebida"), ("otr", "Otro")], max_length=3),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TableSizes",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("size_name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=200)),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.location")),
                ("size", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.tablesizes")),
            ],
        ),
        migrations.CreateModel(
            name="SaleProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cost", models.DecimalField(decimal_places=2, max_digits=6)),
                ("amount", models.IntegerField()),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.product")),
                ("sale", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.sale")),
            ],
        ),
        migrations.AddField(
            model_name="sale",
            name="table",
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to="products.table"),
        ),
        migrations.AddField(
            model_name="product",
            name="subproduct_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.subtype"),
        ),
    ]
